stages:
  - e2e

e2e:
  stage: e2e
  interruptible: false
  services:
    - python:3.8
    - selenium/hub:latest
    - selenium/node-chrome:latest
  script:
    - pip install -r requirements.txt
    - bash run_test_page.sh


#test:
#  stage: test
#  image: $CMS_IMAGE_NAME
#  variables:
#    HUB_HOST: selenium
#    HUB_PORT: 4444
#    START_XVFB: 'false'
#  services:
#    - name: $DB_IMAGE_NAME
#      alias: db
#    - name: selenium/hub:3.141.59-titanium
#      alias: selenium
#    - name: selenium/node-firefox:3.141.59-titanium
#  script:
#    - export LIVE_TEST_CASE_HOST=$(ip addr show eth0 | grep inet | awk '{ print $2 }' | sed -En 's/^([^/]+)\/.*/\1/p'
#    - cd /code
#    - coverage run manage.py test
