stages:
  - e2e

e2e:
  stage: e2e
  interruptible: false
  script:
    - bash run_test_page.sh

selenium-1:
  stage: e2e
  image: selenium/node-chrome:latest
  shm_size: '2gb'
  depends_on:
    - selenium-hub
  environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

selenium-2:
  stage: e2e
  image: selenium/node-chrome:latest
  shm_size: '2gb'
  depends_on:
    - selenium-hub
  environment:
    - SE_EVENT_BUS_HOST=selenium-hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

selenium-hub:
  stage: e2e
  image: selenium/hub:latest
  expose:
    - 4444

#test:
#  stage: test
#  image: $CMS_IMAGE_NAME
#  variables:
#    HUB_HOST: selenium
#    HUB_PORT: 4444
#    START_XVFB: 'false'
#  services:
#    - name: $DB_IMAGE_NAME
#      alias: db
#    - name: selenium/hub:3.141.59-titanium
#      alias: selenium
#    - name: selenium/node-firefox:3.141.59-titanium
#  script:
#    - export LIVE_TEST_CASE_HOST=$(ip addr show eth0 | grep inet | awk '{ print $2 }' | sed -En 's/^([^/]+)\/.*/\1/p'
#    - cd /code
#    - coverage run manage.py test
